# Generated by Django 4.2.5 on 2023-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_due_date_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
